### ISSUE TITLE
Non l10n strings

### ISSUE THREAD

**Issue by nixel2007** [silverbulleters/sonar-l10n-ru#6]
Summary issue for the accumulation of places (and screenshots), which can not be localized in the current version of SonarQube.
- Login screen
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268261/a5c8cf1c-742b-11e6-95c7-04d062dc8af8.png)
- Issues and Effort widget
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268327/ea0b1f2c-742b-11e6-8a00-a5e7b2f039ff.png)
- issues/search page
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268362/0d80c966-742c-11e6-97cd-fdbfc17a3e9e.png)
- "New issues" filter
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268384/282fe6de-742c-11e6-927b-07ded099c12b.png)
- Project overview
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268419/5370a34c-742c-11e6-9b16-4f9da42006f6.png)
- "Events" section on project overview
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268483/9efc7354-742c-11e6-94ed-c57a23c4b037.png)
- Quality profile - changelog of profile
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268538/e4a2480c-742c-11e6-9b9a-00094880678b.png)
- Administration - Configuration drop down menu
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268590/1f60925a-742d-11e6-9fd4-68cea519cd7b.png)
- Administration - Configuration - Custom metric page
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268623/44292d22-742d-11e6-956a-006f4f328564.png)
- Administration - Configuration - Custom metric page - Create metric
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268630/4d507d74-742d-11e6-8994-8a89f8ce9a08.png)
- Administration - Configuration - Global options - all descriptions of properties in all sections
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268671/7914f0d4-742d-11e6-91f1-a0e0f3e7554b.png)
- Administration - Security - Users
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268705/a353091c-742d-11e6-9231-ebc685ee59a6.png)
- Administration - Security - Users - Create user
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268724/b740f40c-742d-11e6-8551-96cd8b25469c.png)
- Administration - Security - Groups
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268754/d8aa1f4c-742d-11e6-84b1-370a69379299.png)
- Administration - Security - Groups - Create group
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268766/e4217910-742d-11e6-8dc7-9efc4a5362dc.png)
- Administration - Security - Global permissions
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268787/fb891702-742d-11e6-8d00-50960b9f5d2d.png)
- Administration - Security - Permissions templates
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268817/236c2f48-742e-11e6-910c-4486341d8f33.png)
- Administration - Security - Permissions templates - Create
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268858/4d196914-742e-11e6-85d6-af4e476be40b.png)
- Administartion - Projects drop down menu
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268863/59aad302-742e-11e6-9167-5014b552437a.png)
- Administartion - Projects - Management
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268884/77497832-742e-11e6-8db9-c14581dc7d5a.png)
- Administartion - Projects - Management - Create project
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268910/86c8bf66-742e-11e6-827d-66b4484cb0ae.png)
- Administartion - Projects - Management - Bulk Apply Permission Template
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268929/9b2420ae-742e-11e6-8ba6-560670073eec.png)
- Administartion - Projects- Background tasks
  ![image](https://cloud.githubusercontent.com/assets/1132840/18268944/b554be66-742e-11e6-866e-55f963a3c9b9.png)
- Administration - System - Update center
  ![image](https://cloud.githubusercontent.com/assets/1132840/18269137/8828fe4c-742f-11e6-9bcb-33cc4a4d7330.png)
- Administration - System - Update center - when no results was found
  ![image](https://cloud.githubusercontent.com/assets/1132840/18269154/9a7a170c-742f-11e6-9779-2cc78a283392.png)
- Administration - System - Update center - plugin install
  ![image](https://cloud.githubusercontent.com/assets/1132840/18269171/ae37aed0-742f-11e6-947b-161eb04955f3.png)
- Administartion - System - About - all parameters and buttons
  ![image](https://cloud.githubusercontent.com/assets/1132840/18269216/d17a1a22-742f-11e6-8d4b-ddb682443225.png)
- /account/projects page
  ![image](https://cloud.githubusercontent.com/assets/1132840/18269249/05fabf0e-7430-11e6-904c-b1ed2fd20c9b.png)
- /account/notifications page - setting notification for project
  ![image](https://cloud.githubusercontent.com/assets/1132840/18269266/177e4674-7430-11e6-9e4c-4388b2967ef4.png)
- /account/security page - generating a new token
  ![image](https://cloud.githubusercontent.com/assets/1132840/18269284/2ff52a88-7430-11e6-9a5e-b5f5a7bbb3b9.png)

**Comment by allustin** [comment]
* edit user groups

![image](https://cloud.githubusercontent.com/assets/55323/18288863/c727627c-7485-11e6-8bc5-551b2aa780b4.png)

**Comment by nixel2007** [comment]
Footer
![image](https://cloud.githubusercontent.com/assets/1132840/21450879/9e91c476-c90b-11e6-905e-32c56f4c7450.png)

New "projects" page:
![image](https://cloud.githubusercontent.com/assets/1132840/21450887/b66ec0d0-c90b-11e6-9168-58091d170cba.png) and all this column

Also text bubbles doesn't resize to text width
![image](https://cloud.githubusercontent.com/assets/1132840/21450893/d5f7d158-c90b-11e6-823c-9b0c1aaf4d98.png)
![image](https://cloud.githubusercontent.com/assets/1132840/21450897/e2483614-c90b-11e6-95b2-b140117074a9.png)

account/security
![image](https://cloud.githubusercontent.com/assets/1132840/21450943/326eee12-c90c-11e6-9f50-c3c0ff439334.png)

**Comment by allustin** [comment]
JIRA link to subscribe https://jira.sonarsource.com/browse/SONAR-8828

**Comment by nixel2007** [comment]
Most of this fixed in 6.6
